name: cielo_ecommerce
description: Pacote para criar pagamentos usando o SDK da API Cielo e-Commerce. Para mais informações acesse a documentação oficial da Cielo e-Commerce para desenvolvedores.
version: 2.2.0
homepage: https://github.com/weldonsouza/cielo_ecommerce

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
